config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    get 'history', on: :collection
    get 'entry_out', on: :member
    get 'detailed_status', on: :collection
    get 'delete_all_customers', on: :collection
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "customers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :contact, :qty, :address, presence: true
  
  before_create :set_in_time
  before_save :set_amount

  def set_in_time
    self.in_time = Time.now + 5.hour + 30.minute if self.in_time.nil?
  end

  def set_amount
    # binding.pry
    self.amount = self.qty*50
  end

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("name LIKE ? OR contact LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy entry_out ]


  # GET /customers or /customers.json
    def index
      if params[:search]
        @customers = Customer.search(params[:search]).order("created_at DESC")
      else
        @customers = Customer.all.order('created_at ASC')
      end
    end


  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_url, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_url, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to history_customers_url, notice: "Customer was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def entry_out
    @customer.out_time = Time.now
    respond_to do |format|
      if @customer.update(out_time: Time.now + 5.hour + 30.minute) 
        format.html { redirect_to customers_url, notice: "Entry Out." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def history
    if params[:search]
      @customers = Customer.search(params[:search]).order("created_at DESC")
    else
      # @customers = Customer.all.order('created_at DESC')
     @customers = Customer.all.where.not(out_time: nil).order('out_time DESC')
    end
    # @customers = Customer.all.where.not(out_time: nil).order('out_time DESC')
  end

  def detailed_status
    
  end

  def delete_all_customers
    respond_to do |format|
      if Customer.delete_all
        format.html { redirect_to customers_url, notice: "Customers were successfully deleted." }
      else
        format.html { redirect_to customers_url, notice: "There is some issue please contact Vishal Soni" }
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :address, :contact, :in_time, :out_time, :qty, :refrence, :out_at, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def total_entry
    Customer.count
  end
  def total_public
    Customer.pluck(:qty).sum
  end
  def total_income
    Customer.pluck(:amount).sum
  end
  def active_public
    Customer.where(out_time: nil).pluck(:qty).sum
  end
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <tr>
    <td><%=customer.name.titleize%></td>         
    <td><%=customer.address.titleize%></td> 
    <td><%=customer.contact%></td>
    <td><%=customer.in_time.strftime('%I:%M %P')%></td>
    <% if customer.out_time != nil %>
      <td><%=customer.out_time.strftime('%I:%M %P')%></td>
    <% end %>
    <td><%=customer.qty%></td>
    <td><%=customer.amount%></td>
    <td><%=customer.refrence%></td>
    <td><%=customer.message%></td>
    <td><%=link_to "Edit", edit_customer_path(customer)%></td>
    <% if customer.out_time.nil? %>
      <td><%=button_to "Out Entry", entry_out_customer_path(customer), method: :get%> </td>
    <% else %>
      <td> <%= button_to "Delete from history", customer, method: :delete %> <td>
    <%end%>  
  </tr>
</div>

<%#if customer.out_time.nil? %>
       <%# <td> </td> %>
    <%# else %>
      <%# <td><%=customer.out_time.strftime('%I:%M %P')</td>  %>
    <%# end %>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label :qty, style: "display: block" %>
    <%= form.number_field :qty %>
  </div>

  <div>
    <%= form.label :refrence, style: "display: block" %>
    <%= form.text_field :refrence %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.label :in_time, style: "display: block" %>
    <%= form.time_field :in_time %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/_header.html.erb
 <tr>
    <th> Name </th>
    <th> Address </th> 
    <th> Contact </th> 
    <th> In Time </th>
    <th> Quantity </th> 
    <th> Amaont </th> 
    <th> Refrence </th> 
    <th> Message </th> 
    <th> Edit </th> 
    <th> Out Entry </th>
</tr>

app/views/customers/_history_header.html.erb
 <tr>
    <th> Name </th>
    <th> Address </th> 
    <th> Contact </th> 
    <th> In Time </th>
    <th> Out Time</th>
    <th> Quantity </th> 
    <th> Amaont </th> 
    <th> Refrence </th> 
    <th> Message </th> 
    <th> Edit </th> 
    <th> Out Entry </th>
</tr>

app/views/customers/detailed_status.html.erb
<p> Total Entry :- <%= total_entry %></p>
<p> Active Public :- <%= active_public %></p>
<div>
  <p> Total Public :- <%= total_public %></p>
  <p> Total Gross :- <%= total_income %></p>
</div></br></br>

<%= button_to "Back to customers", customers_path, method: :get  %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/history.html.erb
<p style="color: green"><%= notice %></p>
<h3>History</h3>
<%= button_to "Back to customers", customers_path, method: :get  %></br>
<%= form_tag(history_customers_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Customers" %>
  <%= submit_tag "Search" %>
<% end %>

</br>
<table>
  <%= render 'history_header' %>
  <div id="customers">  
    <% @customers.each do |customer| %>
        <%= render customer %>
    <% end %>      
  </div>
</table>

</br></br></br></br></br>
<%= button_to "Delete all Customer", delete_all_customers_customers_path, method: :get, class: 'btn-btn-dange'  %></br>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>
<h3>Entry</h3></br>
<%= button_to "New customer", new_customer_path, method: :get %>
<%= button_to "History", history_customers_path, method: :get %>
</br>
<%= form_tag(customers_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Customers" %>
  <%= submit_tag "Search" %>
<% end %>

</br>
<table>
  <%= render 'header' %>
  <div id="customers">  
    <% @customers.each do |customer| %>
      <% if customer.out_time.nil? %>
        <%= render customer %>
      <% end %>  
    <% end %>
  </div>
</table>
</br>
<p> Active Public :- <%= active_public %></p>
<%=button_to "Detail of the day", detailed_status_customers_path, method: :get %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>
  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<!DOCTYPE html>
<html>
  <head>
    <title>Entry</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>